apiVersion: skaffold/v1beta2
kind: Config
build: 
    local:
        push: false
    artifacts:
        -   image: yevhencrowdincom/dockedboilerplate_frontend
            context: frontend
            docker:
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
                '**/*.scss': .
                '**/*.css': .
                '**/*.html': .
        -   image: yevhencrowdincom/dockedboilerplate_backend
            context: backend
            docker:
                dockerfile: Dockerfile.dev
            sync:
                '**/*.js': .
deploy:
    kubectl:
        manifests:
            -   k8s/frontend-deployment.yaml
            -   k8s/backend-deployment.yaml
            -   k8s/database-deployment.yaml
            -   k8s/backend-service.yaml
            -   k8s/database-service.yaml
            -   k8s/frontend-service.yaml
            -   k8s/ingress-service.yaml